### PR TITLE
Export failed wrapper(s) path to `GITHUB_OUTPUT`

### PR DESCRIPTION
**Pull request by jorgectf**
This makes the workflow aware of the path of the JARs that failed validation in favor of an extended analysis or reporting.

### CODE REVIEW

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Comment by JLLeitschuh** [comment]
@eskatos mind merging and releasing?

**Comment by bigdaz** [comment]
Merged

**Comment by bigdaz** [comment]
I had to create a separate PR to resolve conflicts in `dist/index.js`.
Thanks for the contribution.

**Comment by bigdaz** [comment]
This change has been released as [v1.1.0](https://github.com/gradle/wrapper-validation-action/releases/tag/v1.1.0) (or simply `v1`).

**Pull request closed without merging**
